# Generated by Django 4.2.26 on 2025-12-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_email_order_fullname_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
